version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
        - dependency-name: "godot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

