name: Publish README

on:
  push:
    branches: [ master ]
    paths:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create README dir
        run: |
            mkdir readme-dir
            cp README.md ./readme-dir
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./readme-dir
          keep_files: true
          external_repository: luxtorpeda-dev/luxtorpeda-dev.github.io
          publish_branch: master
