name: Sync to Codeberg

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/luxtorpeda/luxtorpeda'
          GIT_USERNAME: d10sfan
          GIT_PASSWORD: ${{ secrets.CODEBERG_KEY }}
